
runtime: php55
api_version: 1

threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /css
  static_dir: assets/css

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /assets
  static_dir: assets

- url: /twitter
  script: twitterscript/twitter_parser.php

- url: /(.*)
  static_files: assets/
  upload: assets/
